version: '3'

services:
  sentiment-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_VERSION=1.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # This could be replaced with your front-end client
  # or another service that consumes the sentiment analysis
  demo-client:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./demo-client:/usr/share/nginx/html
    depends_on:
      - sentiment-service